# Generated by Django 5.2.1 on 2025-05-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surprisekaroapp', '0003_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourstory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='story/')),
            ],
        ),
    ]
