# Generated by Django 5.2.1 on 2025-05-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surprisekaroapp', '0004_ourstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(max_length=225, null=True),
        ),
    ]
