# Generated by Django 5.2.1 on 2025-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surprisekaroapp', '0006_whatsapp_alter_ourstory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
