# Generated by Django 5.2.1 on 2025-05-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surprisekaroapp', '0007_ourstory_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourstory',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='ourstory',
            name='description2',
            field=models.TextField(null=True),
        ),
    ]
